Log messages of /home/loop/.gdesklets/logs/gdesklets%3A0.0.log

==========================================================[05/28/16-07:37:34]===
Adding "/usr/lib/gdesklets/Displays/Calendar/Calendar.display" with ID "id14644138539963248" to the desklet list.



==========================================================[05/28/16-07:37:34]===
Warning: Couldn't read file "/usr/lib/gdesklets/Displays/Calendar/".



==========================================================[05/28/16-07:37:34]===
Couldn't read file /usr/lib/gdesklets/Displays/Calendar/.




==========================================================[05/28/16-07:37:35]===
Warning: Couldn't read file "/usr/lib/gdesklets/Displays/Calendar/".



==========================================================[05/28/16-07:37:35]===
Couldn't read file /usr/lib/gdesklets/Displays/Calendar/.




==========================================================[05/28/16-07:37:56]===
Adding "/usr/lib/gdesklets/Displays/Clock/clock.display" with ID "id14644138761653085" to the desklet list.



==========================================================[05/28/16-07:38:49]===
Adding "/usr/lib/gdesklets/Displays/Quote-of-the-Day/quote.display" with ID "id14644139292813075" to the desklet list.



==========================================================[05/28/16-07:38:49]===
Warning: Couldn't read file "/usr/lib/gdesklets/Displays/Quote-of-the-Day/".



==========================================================[05/28/16-07:38:49]===
Couldn't read file /usr/lib/gdesklets/Displays/Quote-of-the-Day/.



Traceback (most recent call last):
  File "/usr/lib/gdesklets/display/DisplayTarget.py", line 418, in f
    _("The <tt>relative-to</tt> property "
UserError
Traceback (most recent call last):
  File "/usr/lib/gdesklets/display/DisplayTarget.py", line 418, in f
    _("The <tt>relative-to</tt> property "
UserError
Traceback (most recent call last):
  File "/usr/lib/gdesklets/display/DisplayTarget.py", line 418, in f
    _("The <tt>relative-to</tt> property "
UserError

==========================================================[05/28/16-07:38:53]===
Adding "/usr/lib/gdesklets/Displays/Quote-of-the-Day/quote.display" with ID "id14644139334118299" to the desklet list.



==========================================================[05/28/16-07:38:53]===
Warning: Couldn't read file "/usr/lib/gdesklets/Displays/Quote-of-the-Day/".



==========================================================[05/28/16-07:38:53]===
Couldn't read file /usr/lib/gdesklets/Displays/Quote-of-the-Day/.



Traceback (most recent call last):
  File "/usr/lib/gdesklets/display/DisplayTarget.py", line 418, in f
    _("The <tt>relative-to</tt> property "
UserError
Traceback (most recent call last):
  File "/usr/lib/gdesklets/display/DisplayTarget.py", line 418, in f
    _("The <tt>relative-to</tt> property "
UserError
Traceback (most recent call last):
  File "/usr/lib/gdesklets/display/DisplayTarget.py", line 418, in f
    _("The <tt>relative-to</tt> property "
UserError

==========================================================[05/28/16-07:40:08]===
Removing "/usr/lib/gdesklets/Displays/Quote-of-the-Day/quote.display" with ID "id14644139292813075" from the desklet list.



==========================================================[05/28/16-07:40:25]===
RuntimeError('Unrecognized image file format',)


/usr/lib/gdesklets/display/TargetImage.py:108: GtkWarning: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
  self.__original_size = self.__widget.get_size()
/usr/lib/gdesklets/display/TargetImage.py:108: GtkWarning: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
  self.__original_size = self.__widget.get_size()
/usr/lib/gdesklets/display/TargetImage.py:104: Warning: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
  self.__widget.set_from_data(data)
